# Generated by Django 5.0.1 on 2024-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('confirmpassword', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
